### Goal

Test new ideas of implementing metrics

### TODO
- Imagine genes as a time series - compute the fourier transform and apply pearson corr.

In [3]:
# code autoreload
%load_ext autoreload
%autoreload 2
import os
import sys

import random
import math
import numpy.random as nr
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats as scistats

import scanpy.api as sc
import anndata as ad
import xarray as xr
import dask.array as da

## init plotly
# from plotly.offline import iplot, init_notebook_mode
# init_notebook_mode(connected=True)
import plotly.io as pio
pio.renderers.default = 'iframe_connected'
import plotly.graph_objs as go

import sklearn



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
sys.path.append(os.path.expanduser("~/Projects/REP/rep"))
import rep.random as rnd

In [5]:
CACHE_DIR="/s/project/rep/cache/"
RAW_DATA_DIR="/s/project/rep/raw/"
PROCESSED_DATA_DIR="/s/project/rep/processed/"

In [ ]:
l2fc = ad.read_h5ad(os.path.join(PROCESSED_DATA_DIR, "gtex/OUTRIDER/l2fc.h5ad"))
l2fc = l2fc[:, ~ np.any(np.isnan(l2fc.X), axis=0)]

# calculate PCA
sc.pp.pca(l2fc)

l2fc

In [5]:
def calc_corrs(data, obs=None, method="pearson"):
    if obs is not None:
        coords = {
            "observations": xr.DataArray(obs.index, dims=("observations", )),
            **obs.to_xarray().rename_dims({"index":"observations"}),
        }
    else:
        coords = None
    
    xrds = xr.DataArray(
        data,
        dims=("observations", "features"),
        coords=coords
    )
    
    if str(method).lower() == "pearson":
        corrs = np.corrcoef(xrds)
    elif str(method).lower() == "spearman":
        corrs = scistats.spearmanr(xrds, axis=1).correlation
    else:
        raise ValueError("unknown correlation method %s" % str(method))
    
    corrs_xr = xr.DataArray(
        corrs,
        dims=("observations_1", "observations_2"),
        coords={
            **{
                key + "_1": (("observations_1",), vals.values) for key, vals in xrds.coords.items() if vals.dims == ("observations",)
            },
            **{
                key + "_2": (("observations_2",), vals.values) for key, vals in xrds.coords.items() if vals.dims == ("observations",)
            },
        }
    )
    return corrs_xr

In [7]:
corrs = calc_corrs(l2fc.X, l2fc.obs, method="spearman")
corrs

<xarray.DataArray (observations_1: 8166, observations_2: 8166)>
array([[ 1.000000e+00, -8.233220e-03,  5.517639e-02, ...,  3.126127e-02,
         1.187960e-02,  2.101145e-04],
       [-8.233220e-03,  1.000000e+00, -3.893159e-02, ..., -2.439356e-03,
        -1.951421e-02,  2.858393e-02],
       [ 5.517639e-02, -3.893159e-02,  1.000000e+00, ...,  1.858253e-02,
        -1.573536e-02, -1.305164e-02],
       ...,
       [ 3.126127e-02, -2.439356e-03,  1.858253e-02, ...,  1.000000e+00,
        -7.934143e-02,  5.313669e-03],
       [ 1.187960e-02, -1.951421e-02, -1.573536e-02, ..., -7.934143e-02,
         1.000000e+00,  2.615297e-02],
       [ 2.101145e-04,  2.858393e-02, -1.305164e-02, ...,  5.313669e-03,
         2.615297e-02,  1.000000e+00]])
Coordinates:
  * observations_1     (observations_1) object 'GTEX-111CU-1826-SM-5GZYN' ... 'GTEX-ZXG5-0005-SM-57WCN'
    individual_1       (observations_1) object 'GTEX-111CU' ... 'GTEX-ZXG5'
    SMATSSCR_1         (observations_1) float64 0.0 2.0 1.

In [8]:
corrs_pca = calc_corrs(l2fc.obsm["X_pca"], l2fc.obs)
corrs_pca

<xarray.DataArray (observations_1: 8166, observations_2: 8166)>
array([[ 1.000000e+00,  1.897561e-01, -2.154363e-01, ...,  4.721927e-02,
         1.577282e-01,  6.047217e-02],
       [ 1.897561e-01,  1.000000e+00, -1.134831e-02, ...,  1.382194e-01,
        -1.712073e-01, -1.682804e-01],
       [-2.154363e-01, -1.134831e-02,  1.000000e+00, ...,  2.255154e-01,
        -4.201826e-01, -2.112321e-02],
       ...,
       [ 4.721927e-02,  1.382194e-01,  2.255154e-01, ...,  1.000000e+00,
        -6.722392e-04,  2.185299e-01],
       [ 1.577282e-01, -1.712073e-01, -4.201826e-01, ..., -6.722392e-04,
         1.000000e+00,  4.920097e-01],
       [ 6.047217e-02, -1.682804e-01, -2.112321e-02, ...,  2.185299e-01,
         4.920097e-01,  1.000000e+00]])
Coordinates:
  * observations_1     (observations_1) object 'GTEX-111CU-1826-SM-5GZYN' ... 'GTEX-ZXG5-0005-SM-57WCN'
    individual_1       (observations_1) object 'GTEX-111CU' ... 'GTEX-ZXG5'
    SMATSSCR_1         (observations_1) float64 0.0 2.0 1.

In [9]:
np.unique(corrs.subtissue_1)

array(['Adipose_Subcutaneous', 'Adipose_Visceral_Omentum',
       'Adrenal_Gland', 'Artery_Aorta', 'Artery_Coronary',
       'Artery_Tibial', 'Brain_Anterior_cingulate_cortex_BA24',
       'Brain_Caudate_basal_ganglia', 'Brain_Cerebellar_Hemisphere',
       'Brain_Cerebellum', 'Brain_Cortex', 'Brain_Frontal_Cortex_BA9',
       'Brain_Hippocampus', 'Brain_Hypothalamus',
       'Brain_Nucleus_accumbens_basal_ganglia',
       'Brain_Putamen_basal_ganglia', 'Breast_Mammary_Tissue',
       'Cells_EBV_transformed_lymphocytes',
       'Cells_Transformed_fibroblasts', 'Colon_Sigmoid',
       'Colon_Transverse', 'Esophagus_Gastroesophageal_Junction',
       'Esophagus_Mucosa', 'Esophagus_Muscularis',
       'Heart_Atrial_Appendage', 'Heart_Left_Ventricle', 'Liver', 'Lung',
       'Muscle_Skeletal', 'Nerve_Tibial', 'Ovary', 'Pancreas',
       'Pituitary', 'Prostate', 'Skin_Not_Sun_Exposed_Suprapubic',
       'Skin_Sun_Exposed_Lower_leg', 'Small_Intestine_Terminal_Ileum',
       'Spleen', 'Stomac

In [10]:
np.unique(corrs.tissue_1)

array(['Adipose Tissue', 'Adrenal Gland', 'Blood', 'Blood Vessel',
       'Brain', 'Breast', 'Colon', 'Esophagus', 'Heart', 'Liver', 'Lung',
       'Muscle', 'Nerve', 'Ovary', 'Pancreas', 'Pituitary', 'Prostate',
       'Skin', 'Small Intestine', 'Spleen', 'Stomach', 'Testis',
       'Thyroid', 'Uterus', 'Vagina', 'nan'], dtype=object)

In [11]:
sel = corrs_pca.sel(observations_1=(corrs_pca.tissue_1 == "Blood")) #, observations_2=(corrs_pca.tissue_2 == "Brain")))
sel = sel.sel(observations_2=np.isin(sel.individual_2, sel.individual_1))
sel = sel.sel(observations_1=np.isin(sel.individual_1, sel.individual_2))
#sel = np.abs(corrs_pca)
sel = sel.sortby(["individual_1", "individual_2"])
#sel = pd.DataFrame(sel.values, columns=sel.observations_2.values, index=sel.observations_1.values)

trace = go.Heatmap(
    z=sel.values,
    x=sel.observations_2,
    y=sel.observations_1,
    colorscale='RdBu',
    zmin=-1,
    zmax=1
)
layout = go.Layout(
    xaxis=dict(
        automargin=True,
    ),
    yaxis=dict(
        automargin=True,
    ),
    width=1500,
    height=1500
)

fig = go.Figure(data=[trace], layout=layout)

pio.show(fig)

#fig, ax = plt.subplots(figsize=(25,25))
#sns.heatmap(sel)

In [12]:
sel = corrs.sel(observations_1=(corrs.tissue_1 == "Blood")) #, observations_2=(corrs_pca.tissue_2 == "Brain"))
sel = sel.sel(observations_2=np.isin(sel.individual_2, sel.individual_1))
sel = sel.sel(observations_1=np.isin(sel.individual_1, sel.individual_2))
sel = sel.sortby(["individual_1", "individual_2"])
#sel = pd.DataFrame(sel.values, columns=sel.observations_2.values, index=sel.observations_1.values)

trace = go.Heatmap(
    z=sel.values,
    x=sel.observations_2,
    y=sel.observations_1,
    colorscale='RdBu',
    zmin=-1,
    zmax=1
)
layout = go.Layout(
    xaxis=dict(
        automargin=True,
    ),
    yaxis=dict(
        automargin=True,
    ),
    width=1500,
    height=1500
)

fig = go.Figure(data=[trace], layout=layout)

pio.show(fig)

#fig, ax = plt.subplots(figsize=(25,25))
#sns.heatmap(sel)

In [13]:
sel = corrs.sel(observations_1=(corrs.tissue_1 == "Blood"), observations_2=(corrs.tissue_2 == "Lung"))
sel = sel.sel(observations_2=np.isin(sel.individual_2, sel.individual_1))
sel = sel.sel(observations_1=np.isin(sel.individual_1, sel.individual_2))
sel = sel.sortby(["individual_1", "individual_2"])
#sel = pd.DataFrame(sel.values, columns=sel.observations_2.values, index=sel.observations_1.values)

trace = go.Heatmap(
    z=sel.values,
    x=sel.observations_2,
    y=sel.observations_1,
    colorscale='RdBu',
    zmin=-1,
    zmax=1
)
layout = go.Layout(
    xaxis=dict(
        automargin=True,
    ),
    yaxis=dict(
        automargin=True,
    ),
    width=1500,
    height=1500,
)

fig = go.Figure(data=[trace], layout=layout)

pio.show(fig)

#fig, ax = plt.subplots(figsize=(25,25))
#sns.heatmap(sel)

In [14]:
x = l2fc.obs.query("(individual == 'GTEX-UPIC') & (tissue == 'Blood')")

sns.scatterplot(x=x.X[0], y=x.X[1])

AttributeError: 'DataFrame' object has no attribute 'X'

In [ ]:
amax_sel = np.abs(sel).argmax(dim="observations_2")
np.abs(sel).max(dim="observations_2")

In [ ]:
best_corr = pd.DataFrame({
    "obs_1" : sel.observations_1.values, 
    "obs_2": sel.observations_2[amax_sel].values, 
    "corr": sel.isel(observations_2 = amax_sel)
})
best_corr.head()

In [ ]:
best_corr_df = sel.isel(observations_2 = amax_sel).to_dataframe("corr")
best_corr_df.head()

In [ ]:
np.size(np.where(best_corr_df.individual_1 == best_corr_df.individual_2)) / best_corr_df.shape[0]

In [ ]:
best_corr_df[best_corr_df.individual_1 == best_corr_df.individual_2][["observations_2", "corr"]].head()

In [ ]:
x = xrds.sel(observations="GTEX-111YS-0006-SM-5NQBE")
y = xrds.sel(observations="GTEX-111YS-0626-SM-5GZXV")


In [ ]:
sc.pl.scatter(raw_data, x="GTEX-111YS-0006-SM-5NQBE", y="GTEX-111YS-0626-SM-5GZXV")

In [ ]:
sel

In [19]:
tissue = blood
other_tissue = lung

tissue_df = pd.DataFrame(tissue.values, columns=tissue.features, index=tissue.observations)
other_tissue_df = pd.DataFrame(other_tissue.values, columns=other_tissue.features, index=other_tissue.observations)


In [23]:
tissue_df.T.corr()

observations              GTEX-111YS-0006-SM-5NQBE  GTEX-1122O-0005-SM-5O99J  \
observations                                                                   
GTEX-111YS-0006-SM-5NQBE                  1.000000                  0.997549   
GTEX-1122O-0005-SM-5O99J                  0.997549                  1.000000   
GTEX-113IC-0006-SM-5NQ9C                  0.996510                  0.998850   
GTEX-113JC-0006-SM-5O997                 -0.996208                 -0.991120   
GTEX-117YW-0005-SM-5NQ8Z                 -0.250057                 -0.198918   
GTEX-1192W-0005-SM-5NQBQ                 -0.788917                 -0.756657   
GTEX-1192X-0005-SM-5NQC3                 -0.979496                 -0.989199   
GTEX-11DXW-0006-SM-5NQ7Y                  0.995768                  0.998670   
GTEX-11DXX-0005-SM-5NQ8B                  0.998193                  0.993694   
GTEX-11DXY-0006-SM-5NQ8N                  0.507571                  0.556735   
GTEX-11DXZ-0006-SM-5LZZH                  0.921364                  0.900761   
GTEX-11EI6-0005-SM-5N9GN                  0.997370                  0.997527   
GTEX-11EMC-0006-SM-5O9DN                 -0.998306                 -0.999089   
GTEX-11EQ8-0006-SM-5P9HJ                 -0.975935                 -0.976240   
GTEX-11EQ9-0006-SM-5LUB6                 -0.951946                 -0.967166   
GTEX-11GS4-0006-SM-5SI9M                  0.983507                  0.976635   
GTEX-11GSO-0005-SM-5O9CA                 -0.979256                 -0.968656   
GTEX-11GSP-0006-SM-5N9EL                 -0.941140                 -0.956955   
GTEX-11I78-0005-SM-5N9GB                  0.997472                  0.999612   
GTEX-11LCK-0005-SM-5O98U                  0.999133                  0.996942   
GTEX-11NSD-0005-SM-5LZZ5                  0.995568                  0.998965   
GTEX-11NUK-0005-SM-5MR5F                 -0.170290                 -0.118227   
GTEX-11NV4-0005-SM-5N9EX                  0.997058                  0.998067   
GTEX-11O72-0006-SM-5O9DB                 -0.656779                 -0.618583   
GTEX-11OC5-0006-SM-5N9FA                  0.996418                  0.999185   
GTEX-11OF3-0006-SM-5O9CM                 -0.977327                 -0.965180   
GTEX-11ONC-0005-SM-5O9CY                 -0.998250                 -0.999500   
GTEX-11P7K-0006-SM-5N9FM                  0.994500                  0.989219   
GTEX-11P81-0006-SM-5NQ7A                  0.993128                  0.986456   
GTEX-11P82-0006-SM-5N9FY                  0.985020                  0.975035   
...                                            ...                       ...   
GTEX-ZDYS-0002-SM-4WKGR                   0.997252                  0.998755   
GTEX-ZE7O-0006-SM-51MTA                   0.729679                  0.765890   
GTEX-ZE9C-0006-SM-4WKG2                   0.994292                  0.996189   
GTEX-ZEX8-0005-SM-4WKGE                   0.993574                  0.998303   
GTEX-ZF28-0005-SM-4WKH3                  -0.919858                 -0.900739   
GTEX-ZF29-0006-SM-4WKGQ                   0.998938                  0.998200   
GTEX-ZF3C-0005-SM-4WWAR                   0.966468                  0.979522   
GTEX-ZG7Y-0006-SM-4WWEA                   0.965672                  0.969334   
GTEX-ZLV1-0005-SM-4WWAP                   0.989529                  0.991590   
GTEX-ZP4G-0006-SM-4WWE6                   0.999233                  0.998795   
GTEX-ZPCL-0006-SM-4WWAS                   0.998724                  0.997372   
GTEX-ZPIC-0005-SM-4WWEB                   0.988524                  0.990367   
GTEX-ZPU1-0006-SM-4WWAT                   0.063962                  0.112462   
GTEX-ZQG8-0005-SM-4YCEH                   0.926351                  0.907278   
GTEX-ZQUD-0005-SM-4YCE5                  -0.850183                 -0.877829   
GTEX-ZT9W-0005-SM-4YCEG                   0.996556                  0.998828   
GTEX-ZTPG-0006-SM-4YCFG                   0.973492                  0.968990   


In [103]:
corrs.individual_1 == corrs.individual_2

<xarray.DataArray (observations_1: 6766, observations_2: 6766)>
array([[ True, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False,  True]])
Coordinates:
  * observations_1      (observations_1) object 'GTEX-111CU-1826-SM-5GZYN' ... 'GTEX-ZXG5-0005-SM-57WCN'
    RNA.Seq_1           (observations_1) object 'SRR1310275' ... 'SRR1382485'
    SRA_Sample_1        (observations_1) object 'SRS623944' ... 'SRS635146'
    sex_1               (observations_1) object 'male' 'male' ... 'male'
    BioSample_1         (observations_1) object 'SAMN02789465' ... 'SAMN02791282'
    Experiment_1        (observations_1) object 'SRX558418' ... 'SRX591953'
    tissue_1            (observations_1) object 'Adipose Tissue' ... 'Blood'
    sub